global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Blockchain nodes
  - job_name: 'blackhole-blockchain'
    static_configs:
      - targets: 
          - 'blockchain-node-1:8080'
          - 'blockchain-node-2:8080'
          - 'blockchain-node-3:8080'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Wallet service
  - job_name: 'blackhole-wallet'
    static_configs:
      - targets: ['wallet-service:9000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
