version: '3.8'

services:
  # BlackHole Core Blockchain Node
  blackhole-blockchain:
    build:
      context: ../core/relay-chain
      dockerfile: ../../bridge-sdk/Dockerfile.blockchain
    container_name: blackhole-blockchain-node
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${BLOCKCHAIN_PORT:-3000}:3000"
      # - "${BLOCKCHAIN_API_PORT:-8080}:8080"  # Commented out to avoid port conflict
    environment:
      - BLOCKCHAIN_PORT=3000
      - API_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DOCKER_MODE=true
    volumes:
      - blockchain-data:/app/data
      - blockchain-logs:/app/logs
    networks:
      - bridge-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # BlackHole Bridge Node (Enhanced with Real Blockchain Integration)
  bridge-node:
    build:
      context: ../
      dockerfile: bridge-sdk/Dockerfile
    container_name: blackhole-bridge-node
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${SERVER_PORT:-8084}:8084"
      - "${METRICS_PORT:-9090}:9090"
    environment:
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-8084}
      - DB_PATH=/app/data/bridge.db
      - LOG_FILE=/app/logs/bridge.log
      - USE_REAL_BLOCKCHAIN=${USE_REAL_BLOCKCHAIN:-true}
      - BLOCKCHAIN_PORT=${BLOCKCHAIN_PORT:-3000}
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - ETHEREUM_WS_URL=${ETHEREUM_WS_URL}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_WS_URL=${SOLANA_WS_URL}
      - BLACKHOLE_RPC_URL=${BLACKHOLE_RPC_URL:-http://blackhole-blockchain:8080}
      - ETHEREUM_BRIDGE_CONTRACT=${ETHEREUM_BRIDGE_CONTRACT}
      - SOLANA_BRIDGE_PROGRAM=${SOLANA_BRIDGE_PROGRAM}
      - BLACKHOLE_BRIDGE_CONTRACT=${BLACKHOLE_BRIDGE_CONTRACT}
      - ETHEREUM_PRIVATE_KEY=${ETHEREUM_PRIVATE_KEY}
      - SOLANA_PRIVATE_KEY=${SOLANA_PRIVATE_KEY}
      - BLACKHOLE_PRIVATE_KEY=${BLACKHOLE_PRIVATE_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - DOCKER_MODE=true
      - REDIS_URL=${REDIS_URL}
      - POSTGRES_URL=${POSTGRES_URL}
    volumes:
      - bridge-data:/app/data
      - bridge-logs:/app/logs
    networks:
      - bridge-network
    depends_on:
      - blackhole-blockchain
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: blackhole-bridge-redis
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bridge-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL for persistent data storage
  postgres:
    image: postgres:15-alpine
    container_name: blackhole-bridge-postgres
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bridge_db
      POSTGRES_USER: bridge
      POSTGRES_PASSWORD: bridge123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - bridge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bridge -d bridge_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: blackhole-bridge-prometheus
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - bridge-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Grafana for monitoring dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: blackhole-bridge-grafana
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "3001:3000"  # Changed from 3000:3000 to 3001:3000 to avoid port conflict
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - bridge-network
    depends_on:
      - prometheus

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: blackhole-bridge-nginx
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - nginx-logs:/var/log/nginx
    networks:
      - bridge-network
    depends_on:
      - bridge-node

volumes:
  blockchain-data:
    driver: local
  blockchain-logs:
    driver: local
  bridge-data:
    driver: local
  bridge-logs:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  nginx-logs:
    driver: local

networks:
  bridge-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET:-172.20.0.0/16}
